### ISSUE TITLE
Memory size - v2

### ISSUE THREAD

**Issue by szogi1910** [ToxicRevolution/CSGORankMeWeb#14]
The problem reappeared - https://github.com/ToxicRevolution/CSGORankMeWeb/issues/13
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 3 bytes) in /home/pggames/domains/project-games.eu/public_html/statystyki/dd2mirage/control/queryFunctions.php on line 47

**Comment by kennyLtv** [comment]
Looking into this now.

**Comment by kennyLtv** [comment]
So this is going to be clunky and slow but it should fix it till we can get a more permanent solution out. If you go to js/leaderboard/leaderboardFunctions.js and change on line 5 the URL for the ajax from leaderboardGrab.php to leaderboardGrabLarge.php I believe it will work temporarily. I am running that leaderboardGrab on a little over 17k entries on my test server. Please let me know if that doesn't fix it for now.

**Comment by szogi1910** [comment]
Unfortunately, it didn't work for me


Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 79 bytes) in /home/pggames/domains/project-games.eu/public_html/statystyki/dd2mirage/control/queryFunctions.php on line 47

**Comment by APet74** [comment]
I have a new permanent solution almost ready for deployment.

**Comment by APet74** [comment]
Szogi, go download the latest release. I made a change to the leaderBoardGrab.php so that it uses server sided data tables.  You will want to rerun the install.php in the /install/ directory as it adds some new information to the config.php which is required. Let me know if you have problems. As always, download the new files, and replace all current files you have.

Thanks.

**Comment by szogi1910** [comment]
After uploading the new version of leaderboards.php returns us communique No data available in table

I suspect the error is in $ sql_details = array where I can not define the name of the table from which to retrieve server data

**Comment by APet74** [comment]
Table name should be pulled from the variable named $table in the
config.php.

**Comment by szogi1910** [comment]
The data in the table was correctly downloaded before the update.
code below, which as you can see has data to connect to the database but when we have several tables it is probably unable to retrieve data using which leaderboards.php displays no data available in table
```
$sql_details = array(
			'user' => 'xxx_user',
			'pass' => 'xxx',
			'db' => 'xxx_rankme',
			'host' => 'localhost'
);
```

**Comment by APet74** [comment]
Just pulled a fresh copy of the repo and it's giving an error. Let me address it real quick.

**Comment by APet74** [comment]
Ok so... I am not the smartest person alive, obviously. I misspelled the AJAX request... So it should work now. You can either redownload the new release OR go into js/leaderboard/leaderboardFunctions.js and at the bottom change  `"ajax": "control/leaderboard/leaderBoardGrab.php", ` to `"ajax": "control/leaderboard/leaderboardGrab.php", ` (board isn't capitalized. Also in views/leaderboards/index.php change kills and deaths to K/D and ADR as that is what is actually being reported not kills and deaths (should be 2 kills and 2 deaths)

**Comment by szogi1910** [comment]
Unfortunately, still does not show details
http://project-games.eu/statystyki/dd2mirage/leaderboards.php

**Comment by APet74** [comment]
As stated above, please change the following inside of `/js/leaderboard/leaderboardFunctions.js':

`"ajax": "control/leaderboard/leaderBoardGrab.php"`
to
`"ajax": "control/leaderboard/leaderboardGrab.php"`

Here is a screenshot that shows that it is still wrong.
http://petrzilkacoding.com/gitHubAPI/ssMemoryError.png
Here is the change in the master code directory: https://github.com/ToxicRevolution/CSGORankMeWeb/blob/master/js/leaderboard/leaderboardFunctions.js#L140

**Comment by APet74** [comment]
I am still checking out your site and it seems to still be down but it looks as though it is down because you haven't placed the new javascript file into the folder. Let me know if this is intentional.

**Comment by szogi1910** [comment]
I uploaded the files, which are new to the github community, and then I reinstalled the script and as you can see on the page the effect

**Comment by APet74** [comment]
Is it broken? It seems to be working when I view it.

**Comment by szogi1910** [comment]
Nie bardzo rozumiem, co teraz masz na myśli

**Comment by APet74** [comment]
Is there still an issue? When I go to your site the table loads and all the data looks proper. Is there still an issue that needs addressing?

**Comment by szogi1910** [comment]
works fine, forcing ctrl + f5 several times

**Comment by APet74** [comment]
We can close this issue then. Thanks!
